version: '3.4'

services:
  dotnet-xplat_docker-webapp-app:
    image: dotnet-xplat/docker-webapp:dev
    build:
      dockerfile: Dotnet.XPlat.Docker.WebApp.App/Dockerfile.Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx