version: '3.4'

services:
  dotnet-xplat_docker-webapi-app:
    image: dotnet-xplat/docker-webapi:dev
    build:
      dockerfile: Dotnet.XPlat.Docker.WebApi.App/Dockerfile.Debug
      target: base
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx